version: '3'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: always
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${UID}
      - PLEX_GID=${GID}
    volumes:
      - ${CONFIG}/plex:/config
      - ${TRANSCODE}:/transcode
      - ${MOVIES}:/data/movies
      - ${TVSHOWS}:/data/tvshows
      - ${AUDIOBOOKS}:/data/audiobooks

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: always
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/transmission:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: always
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/jackett:/config
      - ${DOWNLOADS}/blackhole:/downloads
    ports:
      - 9117:9117

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: always
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${MOVIES}:/movies
      - ${TVSHOWS}:/tvshows
    ports:
      - 6767:6767

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: always
    network_mode: host
    depends_on:
      - transmission
      - jackett
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
      - ../scripts:/scripts
    ports:
      - 7878:7878

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: always
    network_mode: host
    depends_on:
      - transmission
      - jackett
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${TVSHOWS}:/tvshows
      - ${DOWNLOADS}:/downloads
      - ../scripts:/scripts
    ports:
      - 8989:8989
