global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80
#    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: replace@example.com
      storage: /ssl-certs/staging.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
         entryPoint: web
  production:
    acme:
      email: replace@example.com
      storage: /ssl-certs/production.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    useBindPortIP: true
  file:
    directory: /etc/traefik
    watch: true

