version: "3"

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    ports:
      - 8096:8096
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${MEDIA}:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.routers.jellyfin.entrypoints=web

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    ports:
      - 32400:32400
    environment:
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${UID}
      - PLEX_GID=${GID}
    volumes:
      - ${CONFIG}/plex:/config
      - ${TRANSCODE}:/transcode
      - ${MEDIA}:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.routers.plex.entrypoints=web

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    ports:
      - 9091:9091
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/transmission:/config
      - ${DOWNLOADS}:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN}`)
      - traefik.http.routers.transmission.entrypoints=web

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    ports:
      - 6767:6767
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${MEDIA}/movies:/movies
      - ${MEDIA}/tvshows:/tvshows
      - ${MEDIA}/animes:/animes
    labels:
      - traefik.enable=true
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)
      - traefik.http.routers.bazarr.entrypoints=web

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878
    depends_on:
      - transmission
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MEDIA}/movies:/movies
      - ${DOWNLOADS}:/downloads
      - ../scripts:/scripts
      - ../.env:/scripts/.env
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.http.routers.radarr.entrypoints=web

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - 8989:8989
    depends_on:
      - transmission
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}/tvshows:/tvshows
      - ${MEDIA}/animes:/animes
      - ${DOWNLOADS}:/downloads
      - ../scripts:/scripts
      - ../.env:/scripts/.env
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.routers.sonarr.entrypoints=web

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
      - LOG_LEVEL=debug
    volumes:
      - ${CONFIG}/overseerr:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN}`)
      - traefik.http.routers.overseerr.entrypoints=web

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG}/prowlarr:/config
    labels:
      - traefik.enable=true
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
      - traefik.http.routers.prowlarr.entrypoints=web
