version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - WEB_PORT=8053
    volumes:
      - ${CONFIG}/pihole/etc-pihole:/etc/pihole
      - ${CONFIG}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=3001
    volumes:
      - ${CONFIG}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

  ddclient:
    container_name: ddclient
    image: lscr.io/linuxserver/ddclient:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG}/ddclinet:/config

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 3600
