version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - WEB_PORT=8053
      - INTERFACE=enp2s0
    volumes:
      - ${CONFIG}/pihole/etc-pihole:/etc/pihole
      - ${CONFIG}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=8053
      - traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)
      - traefik.http.routers.pihole.entrypoints=web

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - ${CONFIG}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
      - traefik.http.routers.portainer.entrypoints=web

  traefik:
    container_name: traefik
    image: traefik:latest
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG}/traefik:/ssl-certs
      - ../config/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=web

  ddclient:
    container_name: ddclient
    image: lscr.io/linuxserver/ddclient:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG}/ddclinet:/config

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    ports:
      - 8084:8080
    environment:
      - TZ=${TIMEZONE}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_APIKEY}
      - WATCHTOWER_HTTP_API_METRICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 3600

  speedtest-tracker:
    container_name: speedtest-tracker
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    ports:
      - 8083:80
    environment:
      - TZ=${TIMEZONE}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/speedtest:/config
    labels:
      - traefik.enable=true
      - traefik.http.services.speedtest.loadbalancer.server.port=80
      - traefik.http.routers.speedtest.rule=Host(`speedtest.${DOMAIN}`)
      - traefik.http.routers.speedtest.entrypoints=web
